# Generated by Django 5.2.7 on 2025-10-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_favorite_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_games',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_genres',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.TextField(blank=True, help_text='Favourite games, genres, or franchises.'),
        ),
    ]
