# Generated by Django 5.2.7 on 2025-10-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_favorite_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_games',
            field=models.TextField(blank=True, help_text='Favorite games separated by commas.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.TextField(blank=True, help_text='Favorite genres separated by commas.'),
        ),
    ]
