# Generated by Django 5.2.7 on 2025-10-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indicates whether the post has passed editorial review.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=120, unique_for_date='published_at'),
        ),
    ]
