# Generated by Django 5.2.7 on 2025-10-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_is_approved_alter_blogpost_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-published_at", "-updated_at"],
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
            },
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="is_approved",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="status",
            field=models.CharField(
                choices=[("approved", "Approved"), ("rejected", "Rejected")],
                default="rejected",
                max_length=10,
            ),
        ),
    ]
