# Generated by Django 5.2.7 on 2025-10-21 20:12

from django.db import migrations, models

try:
    import cloudinary.models
except ImportError:  # pragma: no cover - optional dependency
    cloudinary = None
else:
    cloudinary = cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_options_remove_blogpost_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=(
                cloudinary.CloudinaryField(
                    verbose_name='image', blank=True, null=True, max_length=255)
                if cloudinary
                else models.ImageField(
                    upload_to='blog_images/', blank=True, null=True)),
        ),
    ]
